### ISSUE TITLE
v0.8.0: hosts doco

### ISSUE THREAD

**Issue by porjo** [mailgun/vulcand#143]
It is not clear from the doco how to associate a frontend with a host. Or to put it another way, how do I configure specific routing for a particular host?

**Comment by klizhentas** [comment]
Added a special section for host based routing in the docs:

http://docs.vulcand.io/proxy.html#routing-language

**Comment by porjo** [comment]
Thanks. 

What does this mean?: 

> None of the example above does not set up hosts entries in Vulcand.

Did you mean to say:

> The example above do not set up host entries in Vulcand

Also, it is not clear to me *where* to use the routing language. Can this be done from command line, or must I implement middleware in Go?

**Comment by klizhentas** [comment]
> Did you mean to say:
>
>    The examples above do not set up host entries in Vulcand

> Also, it is not clear to me where to use the routing language. Can this be done from command line, > or must I implement middleware in Go?

Every Vulcand frontend has a special Route field for routing requests.

**Comment by porjo** [comment]
Ah, that was the missing piece of the puzzle. Thanks!
