### ISSUE TITLE
gzip

### ISSUE THREAD

**Issue by porjo** [mailgun/vulcand#147]
Testing v0.8.x 

Vulcand is returning zero-length content when the backend server sends gzipped content.

For example, the following header is returned by my backend:

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Encoding: gzip
Content-Type: image/png
Last-Modified: Thu, 01 Jan 2015 03:54:08 GMT
Vary: Accept-Encoding
Date: Thu, 01 Jan 2015 04:02:36 GMT
Transfer-Encoding: chunked
```

The client sees the following header instead:

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Type: image/png
Date: Thu, 01 Jan 2015 04:02:36 GMT
Last-Modified: Thu, 01 Jan 2015 03:54:08 GMT
Vary: Accept-Encoding
Content-Length: 0
```

This wasn't an issue with previous vulcand version. Disabling gzip on the backend resolves the issue.

**Comment by porjo** [comment]
That's fixed for me. Thanks.

**Comment by klizhentas** [comment]
Ok, closing then
