### ISSUE TITLE
tls listener

### ISSUE THREAD

**Issue by porjo** [mailgun/vulcand#148]
I'm trying to get TLS working with v0.8.x but not having much luck (I did have it working with prior version).

These are the config steps I've taken:

```
etcdctl set /vulcand/listeners/ls1/ '{"Protocol":"https", "Address":{"Network":"tcp", "Address":":8183"}}'
etcdctl set /vulcand/hosts/host1.com/keypair 'sealed key here'
```

After that vulcand would fail on startup with this message:

```
Jan 01 06:25:46 bris01 docker[22882]: Service exited with error: service start failure: 100: Key not found (/vulcand-bris01/hosts/host1.com/host
```

Creating an empty key seemed to fix that:
```
etcdctl set /vulcand/hosts/host1.com/host '{"Settings": {}}'
```

Is that necessary??

Now vulcand starts OK and is listening on port `8183` however is not handling TLS connections.

Attempting to update the `host` key while vulcand is running results in a panic:

```
Jan 01 06:43:39 bris01 docker[23187]: Jan  1 06:43:39.316: INFO PID:1 [mux.go:224] mux(2, active) UpsertHost Host(host1.com)
Jan 01 06:43:39 bris01 docker[23187]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 01 06:43:39 bris01 docker[23187]: [signal 0xb code=0x1 addr=0x0 pc=0x572e2b]
Jan 01 06:43:39 bris01 docker[23187]: goroutine 104 [running]:
Jan 01 06:43:39 bris01 docker[23187]: runtime.panic(0x847c40, 0xb25593)
Jan 01 06:43:39 bris01 docker[23187]: /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
Jan 01 06:43:39 bris01 docker[23187]: github.com/mailgun/vulcand/proxy.(*srv).upsertKeyPair(0xc2080a4000, 0xc208286706, 0xc, 0x0, 0x0, 0x0)
Jan 01 06:43:39 bris01 docker[23187]: src/github.com/mailgun/vulcand/proxy/srv.go:105 +0x15b
```

**Comment by klizhentas** [comment]
Note that config format for the host in etcd has changed. Threre's no more `keypair`.
Instead there's only one property `host` that contains all the settings including the keypair:

```
etcdctl set /vulcand/hosts/host1.com/host '{"Settings": {"KeyPair": "encrypted-key-pair"}}'
```

The easiest way to set that is to use 

```
vctl upsert_host -name host1.com -cert=/path -key=/path
```

The tool will do the proper serialization for you.

**Comment by klizhentas** [comment]
I will fix the panic though just in case

**Comment by porjo** [comment]
Thankyou, I have it working now using the following command: 
```
vctl host upsert -name host1.com --cert=/path --privateKey=/path
```

Could you please update the TLS section of the doco when you get a chance.

**Comment by klizhentas** [comment]
Sure, 

I did not actually realise that it was outdated

**Comment by klizhentas** [comment]
Fixed
