### ISSUE TITLE
Support encoded "&" in routing rules

### ISSUE THREAD

**Issue by robszumski** [mailgun/vulcand#165]
AFAICT, Go's json marshaling will escape `<`, `>`, `&` because of security implications. Vulcan should support rules formatted this way.

```
$ etcdctl get /vulcand/frontends/robszumski/frontend
{"Type":"http","BackendId":"robszumski","Route":"Host('robszumski.com') \u0026\u0026 PathRegexp('/.*')"}
```

**Comment by porjo** [comment]
I've just tested this with one of my frontends, replacing `&&` with `\u0026\u0026` and it worked fine. What problem are you seeing?

**Comment by robszumski** [comment]
I backed off this work so I'll go ahead and close. Thanks for testing it out.
