### ISSUE TITLE
No response body from circuit breaker middleware

### ISSUE THREAD

**Issue by jamesrwhite** [mailgun/vulcand#170]
Hey,

I've been testing out the circuit breaker using the latest version from master at the time of writing and while I can correctly trigger the breaker and see it setting the content type and response code the body is never set for the fallback response.

I've tried using the example in the docs and this also but neither worked:

````
etcdctl set /vulcand/frontends/f1/middlewares/cb1 '{
    "Id": "cb1",
    "Priority": 1,
    "Type": "cbreaker",
    "Middleware": {
        "Condition": "NetworkErrorRatio() < 1.0",
        "Fallback": {
            "Type": "response",
            "Action": {
                "StatusCode": 400,
                "Body": "[1, 2, 3]",
                "ContentType": "application/json"
            }
        },
        "FallbackDuration": 10000000000000,
        "RecoveryDuration": 100000000,
        "CheckPeriod": 100000000
    }
}'
````

The rest of the config we have is:

````
etcdctl set /vulcand/backends/b1/backend '{"Type": "http", "Settings": {"KeepAlive": {"MaxIdleConnsPerHost": 1024, "Period": "5s"}}}'
etcdctl set /vulcand/backends/b1/servers/srv1 '{"URL": "http://httpbin.org"}'
etcdctl set /vulcand/frontends/f1/frontend '{"Id":"f1","Route":"Path(\"\/get\")","Type":"http","BackendId":"b1"}
````

I've been testing this using curl and I can see using the `-I` flag that the content type/response code are set but without that I don't get any response body.

**Comment by klizhentas** [comment]
Thanks for the report, I will take a look into this

**Comment by jamesrwhite** [comment]
Thanks, let me know if there's any more info I can prove to help out :)

**Comment by jamesrwhite** [comment]
Any word on this, are you able to use it successfully?
