### ISSUE TITLE
vulcand is mangling x-forwarded-for and x-forwarded-proto headers

### ISSUE THREAD

**Issue by wonderlic-stephene** [mailgun/vulcand#175]
I have vulcand running on a CoreOS cluster behind an Amazon Elastic Load Balancer (ELB) with SSL offload.

I created a dummy application that just prints out the request's headers to verify some things, and found that vulcand is mangling at least two of the expected headers.

If I remove vulcand from in between the ELB and my application, the X-Forwarded-For has the end user's IP address and the X-Forwarded-Proto properly has 'https'.  When vulcand is in-between the ELB and my application, the X-Forwarded-For has an IP address on one of my internal subnets that looks like it might be associated with the ELB and the X-Forwarded-Proto changes to 'http'.

According to http://tools.ietf.org/html/rfc7239#section-5.2 the X-Forwarded-For header is supposed to be a comma separated list of IP Addresses with the client's being the leftmost and each successive proxy added to the right.

Similarly, according to http://tools.ietf.org/html/rfc7239#section-5.4 the X-Forwarded-Proto header is supposed to indicate the protocol that the client used, and not necessarily the protocol that the proxy/server received.  Without this being forwarded properly, it breaks a lot of implementations where the server's config (i.e. nginx) is looking at this header to determine if it needs to redirect the user to the secure version of the website.  With this bug, it causes an endless redirection loop.

**Comment by wonderlic-stephene** [comment]
I will leave up my dummy application for a few days in order to allow others to see the headers received in either case

Here is the version with vulcand in the middle:
https://node-hello.wonderlic.com/
http://node-hello.wonderlic.com/

And, here is the version without vulcand in the middle:
https://node-hello2.wonderlic.com/
http://node-hello2.wonderlic.com/

**Comment by stith** [comment]
+1

Running the vulcand docker container, X-Forwarded-For is being set to docker's gateway IP. A mechanism to have Vulcand set X-Forwarded-For itself would be great.

**Comment by porjo** [comment]
There is a bool field called `TrustForwardHeader` which can be set when defining your frontend which should give you the behaviour you want e.g.

```
etcdctl set /vulcand/frontends/f1/frontend \
 '{"Type": "http", "BackendId": "b1", "Route": "Path(`/`)", "Settings": {"TrustForwardHeader": true}}'
```

I haven't tested it myself, but I can see from the code [here](https://github.com/mailgun/vulcand/blob/master/Godeps/_workspace/src/github.com/mailgun/oxy/forward/rewrite.go#L21) that it will cause previous hops to be included.

**Comment by wonderlic-stephene** [comment]
Yep, that worked.  I updated my example above, and it is now setting the x-forwarded-for and x-forwarded-proto headers properly.
