### ISSUE TITLE
Route not matchin Host

### ISSUE THREAD

**Issue by Zapadlo** [mailgun/vulcand#180]
Can't for the life of me figure out what I'm doing wrong.

This is my request:

    curl -i -X PUT -H "Host: Mongo-Writer" -H "Content-Type: application/json" -d "" http://localhost:8080/content/3378ac39-32f9-4106-9884-27cb7dc77877

Which works with the following frontend:

    {"Type": "http", "BackendId": "mongo-writer", "Route": "PathRegexp(`/.*`)"}

From vulcand logs: 

    Mar 04 21:07:14 thinkpad bash[13452]: Mar  4 21:07:14.888: INFO PID:1 [fwd.go:103] Round trip: http://172.17.42.1:49185, code: 400, duration: 3.676313ms

If however I change it to:

    {"Type": "http", "BackendId": "mongo-writer", "Route": "PathRegexp(`/.*`) && Host(`Mongo-Writer`)"}

I get:

    Mar 04 21:13:23 thinkpad bash[13452]: Mar  4 21:13:23.928: INFO PID:1 [mux.go:587] Not found: PUT /content/3378ac39-32f9-4106-9884-27cb7dc77877

I tried, switching quotes for double quotes and single quotes, using HostRegepx, Header, HeaderRegexp, using Host on its own in Route, using "localhost" as value in case the header is ignored with the same result.

Is this a bug, or am I misunderstanding how vulcand behaves?

Ta

**Comment by porjo** [comment]
Check your string escaping, for example `Host(Mongo-Writer)` should probably be ``Host(`Mongo-Writer`)``. See http://www.vulcanproxy.com/proxy.html#frontends for more examples.

**Comment by Zapadlo** [comment]
I think I have, I tried:
`
{"Type": "http", "BackendId": "mongo-writer", "Route": "PathRegexp(`/.*`) && Host(`Mongo-Writer`)"}
{"Type": "http", "BackendId": "mongo-writer", "Route": "PathRegexp('/.*') && Host('Mongo-Writer')"}
{"Type": "http", "BackendId": "mongo-writer", "Route": "PathRegexp(\"/.*\") && Host(\"Mongo-Writer\")"}
`

**Comment by porjo** [comment]
OK, sorry - I see now that the markdown was messing up where your quotes were!

Do you get the same error when doing a `GET` on `/` e.g.
```
curl -i -H "Host: Mongo-Writer" http://localhost:8080/
```

Also try enabling debug i.e. `vulcand -logSeverity=DEBUG`

**Comment by Zapadlo** [comment]
Yep, same error requesting `/`.

I have enabled INFO level logging, don't think DEBUG is a valid value.

**Comment by klizhentas** [comment]
Hey, sorry for the slow response, I will try to reproduce and will get back to you

**Comment by Zapadlo** [comment]
Problem was case sensitivity of the HOST headers. 
The Header on the request was being converted to lowercase but read from ETCD raw.
PR: https://github.com/mailgun/vulcand/pull/181

**Comment by klizhentas** [comment]
Thanks for digging in, really appreciate it!
