### ISSUE TITLE
Allow vulcand to set x-forwarded-for

### ISSUE THREAD

**Issue by stith** [mailgun/vulcand#183]
My request flow right now is vulcand in a docker container, which forwards to a Heroku buildpak, also running in a docker container. It seems that vulcand is setting the x-forwarded-for to "172.17.42.1" for all of my requests, rather than setting it to the actual source IP of the request. Enabling "TrustForwardHeader" won't do the trick here, since it seems like that'd allow users to forge their IPs by sending their own x-forwarded-for.

**Comment by porjo** [comment]
What IP address should your HTTP client be coming from? If you're running your web browser on the same host as Docker, then the client IP may legitimately be 172.17.42.1

**Comment by stith** [comment]
All of my tests have been remote, just with a browser on my computer. I'd expect the IP to show up as the remote user's IP address.

**Comment by porjo** [comment]
Vulcand sets `x-forwarded-for` to be whatever is in `http.Request.RemoteAddr`. Perhaps you could verify by running tcpdump inside your vulcand container to check the source IP of the incoming HTTP request e.g.`tcpdump -i eth0 port 80 -tnn`. If that is set to `172.17.42.1` then the issue is not with vulcand.

**Comment by stith** [comment]
Hmm, seems like this was more a docker problem than a vulcand problem. I switched to using host networking in the container, otherwise the request gets routed through the docker0 interface which resets the source address. Thanks for pointing me in the right direction!
