### ISSUE TITLE
Port Param has no Effect

### ISSUE THREAD

**Issue by vanthome** [mailgun/vulcand#193]
Hi,

I'm running vulcand outside a container and maybe this bug has not been reported yet.
The `-port=` param does not have any effect.
If I start vulcand with it, it will still listen on port 8181 (ipv4) and  8182 (ipv6).

thanks

**Comment by porjo** [comment]
Works for me!

I've compiled vulcand from latest commit, run like so:
```
 ./vulcand -port=8000 -etcd=http://172.17.42.1:4001
```
I can see it is listening on the specified port:
```
$ netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 172.17.0.16:37006       xxx.xxx.xxx.176:4001     ESTABLISHED 10/vulcand
tcp        0      0 172.17.0.16:43728       172.17.42.1:4001        ESTABLISHED 10/vulcand
tcp        0      0 :::8182                 :::*                    LISTEN      10/vulcand
tcp        0      0 :::8000                 :::*                    LISTEN      10/vulcand
```

What version of Vulcand are you using, and what are your exact command line arguments?

**Comment by vanthome** [comment]
Hi thanks!

I'm using the latest release `v0.8.0-beta.2`.
The commandline is:

`./vulcand -interface=xxx -etcd=http://192.168.10.2:2379 http://192.168.10.1:2379 -port=80 --logSeverity=INFO`

--> works not!

Now I found out, it works when moving the `port=xxx` param more to the bginning:

`./vulcand -interface=xxx -port=80 -etcd=http://192.168.10.2:2379 http://192.168.10.1:2379  --logSeverity=INFO`

--> works!

So obviously a problem with command line parsing.

**Comment by porjo** [comment]
Ah, that explains it. The way you are defining `etcd` is messing up the command-line arguments. AFAIK any argument that has multiple values must be either listed multiple times e.g.:
```
-etcd=http://192.168.10.2:2379 -etcd=http://192.168.10.1:2379
```
or once, with multiple values separated by a comma:
```
-etcd=http://192.168.10.2:2379,http://192.168.10.1:2379
```

Because you are using a space, the command arguments are getting messed up, causing `-port` not to be read properly.

**Comment by vanthome** [comment]
Yea, tat's it :) Just verified it. To make things celarer, let's address [this](https://github.com/mailgun/vulcand/issues/194)

**Comment by porjo** [comment]
> the comma seperated variant does not work

Sorry, you are right - looks like only the first way is valid.
