### ISSUE TITLE
Allow a user-provided NotFound middleware to be passed into mux

### ISSUE THREAD

**Issue by archisgore** [mailgun/vulcand#201]
This has been brought up in various other forms many times. What we need to make vulcan work, is to audit/log/manage anytime vulcan didn't match an incoming route.

For this, I would like the ability to pass in a Middleware that replaces NotFound middleware.

I created a quick form to test out how it would look for me. This isn't the best-written code-reviewable code, but illustrates the concept.
https://github.com/polyverse-security/vulcand-fork

The idea is, either in etcd there could be a "NotFound" frontend into which we can insert middleware chains just like we'd do for a matching frontend. Or we could say that NotFound is such a very specific narrow case, that it doesn't need to be configurable, and then we pass in an extra NotFound field in the Registry struct alongside the other middlewares, which is passed into mux.

I can clean up the code and submit a pull request for that to illustrate the diff.

**Comment by archisgore** [comment]
I created a pull request.
https://github.com/mailgun/vulcand/pull/202

This is reference code, but I'm totally open to suggestions, alternatives, and ideas.

**Comment by klizhentas** [comment]
this is implemented by @archisgore in #202, thanks for your time!
