### ISSUE TITLE
healthcheck on backend servers?

### ISSUE THREAD

**Issue by arjanschaaf** [mailgun/vulcand#203]
Hi,

I'm new to vulcand and am used to Amazon Elastic Load Balancers & HAProxy. With ELB & HAProxy I'm used to configuring a health check on my backend servers. If the health check passes (for example a GET on /healthcheck returns 200 or the body contains ("OK!") the server is active in the backend pool. If not, ELB or HAProxy won't send any traffic to that server until the health check is successful again.
I've read the documentation on the circuit breakers, which is a great tool which more or less deals with the same situation. However I think the scope of health checks and circuit breakers is a bit different. Health checks deal with the situation when the backend knows it is not healthy. Circuit breaks deal with the situation when the backend doesn't know whether it is healthy or not.

Does vulcand currently offer anything to implement such health checks on your backend servers?

**Comment by fracklen** [comment]
IMO, this is outside the scope of vulcand. That's a job for the sidekick.

The way we use vulcand, is by having a sidekick per application. This sidekick is application specific, and knows how to do health-checks.

You can get inspiration from our https://github.com/lokalebasen/sidekick, which is also available as the docker image `lokalebasen/sidekick`.

We've implemented it, so the sidekick writes the backend to `etcd` with a timeout of 180 secs. The health-check is queried every 60 secs. If the health-check fails, the backend server is unregistered.
If the sidekick should crash - for whatever reason, the backend server times out.

That works great for us at [Lokalebasen.dk](http://www.lokalebasen.dk)

**Comment by arjanschaaf** [comment]
Hi,

You're right: doesn't have to be the responsibility of vulcand itself. I like your setup, thanks for sharing.
btw: have you thought about adding webhooks like the circuit breaker functionality offers?

**Comment by fracklen** [comment]
Haven't had the need for it yet, but good idea. I'm considering adding amqp-hooks. But webhooks is definitely a good idea.
