### ISSUE TITLE
Make backend datastore pluggable

### ISSUE THREAD

**Issue by SEJeff** [mailgun/vulcand#209]
I would love to find a way to see if vulcand could be used for service discovery and load balancing of tasks on an [Apache Mesos](http://mesos.apache.org/) cluster running tasks under [Aurora](http://aurora.apache.org/).

Aurora publishes task information to (boo) zookeeper using a relatively standard thing twitter invented called Server Sets. It would be great if there was a way to get vulcand to proxy/loadbalance for aurora tasks.

Would this ever be considered, or should I just setup etcd inside mesos (meh) and rig up some machinery to sync state between the two?

**Comment by 3onyc** [comment]
Vulcand already has pluggable datastores (called engines), see [engine/engine.go](https://github.com/mailgun/vulcand/blob/master/engine/engine.go) for the interface. There's no engine for ZooKeeper/ServerSet though, so that would need to be implemented.
