### ISSUE TITLE
Disable the default listener

### ISSUE THREAD

**Issue by archisgore** [mailgun/vulcand#244]
I was wondering if there's a way to disable the default listener. Here's the explicit use case I'm interested in.

For compliance reasons, some systems in our application must ALWAYS be on SSL. Now we take all precautions to make sure SSL is used by clients, however, it would be very cool, if we were able to use vulcan to ensure that the only listener that is active is the SSL-based listener, and to kill all other traffic.

Any ideas how I can do this?

**Comment by klizhentas** [comment]
yep, we can make it a startup flag --no-default-listener. In this case vulcand would not set up a default listener here:

https://github.com/mailgun/vulcand/blob/master/service/service.go#L307

**Comment by archisgore** [comment]
Awesome. Thanks for pointing it out. Would have taken me a couple of days to nail that.

**Comment by archisgore** [comment]
Created a PR. That was simpler than I thought.
https://github.com/mailgun/vulcand/pull/245

**Comment by klizhentas** [comment]
have you tried it?

**Comment by archisgore** [comment]
Yup. I just ran it - works perfectly.
